networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
    external:
      name: ${COMPOSE_PROJECT_NAME}.backend

services:
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}.nginx
    networks:
      - frontend
      - backend
    ports:
      - "8001:80"
    volumes:
      - ./build/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - golang
    labels:
      traefik.enable: true
      traefik.admin.frontend.rule: "Host:${APP_DOMAIN};PathPrefix:${ADMIN_PATH}"
      traefik.admin.frontend.whiteList.useXForwardedFor: true
      traefik.front.frontend.rule: "Host:${APP_DOMAIN}"
      traefik.front.frontend.whiteList.useXForwardedFor: true
      traefik.frontend.redirect.entryPoint: "https"
      traefik.port: 80
      traefik.protocol: "http"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
